---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu
  driver_config:
    box: ubuntu
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    customize:
      memory: 1024

suites:
- name: default
  run_list: ['recipe[cookbook-pipeline]']
